import type { ProjectModel, InterviewMessage } from './types'

export const mockProject: ProjectModel = {
  project_id: 'proj_001',
  org_id: 'org_001',
  status: 'interviewing',
  overall_confidence: 58,
  sections: {
    purpose: {
      label: '목적',
      value: '사내 인사관리 시스템을 클라우드 기반 SaaS로 전환하여, 재택근무 환경에서도 인사 업무를 원활하게 처리할 수 있도록 함.',
      confidence: 85,
      source: 'document',
      source_refs: ['doc_001'],
      updated_at: '2026-07-03T10:00:00Z',
    },
    current_operation: {
      label: '현재 운영방식',
      value: '온프레미스 ERP(SAP HR 모듈) + 엑셀 기반 수동 관리. 급여 계산은 월 1회 수작업.',
      confidence: 70,
      source: 'document',
      source_refs: ['doc_001'],
      updated_at: '2026-07-03T10:00:00Z',
    },
    users: {
      label: '사용자',
      value: '인사팀 5명, 각 부서 팀장 20명, 전체 직원 300명 (셀프서비스)',
      confidence: 60,
      source: 'document',
      source_refs: ['doc_002'],
      updated_at: '2026-07-03T10:05:00Z',
    },
    core_problem: {
      label: '핵심 문제',
      value: '재택근무 전환 후 출퇴근/휴가 관리가 엑셀로 회귀. 인사팀 업무 부하 2배 증가.',
      confidence: 90,
      source: 'document',
      source_refs: ['doc_001', 'doc_002'],
      updated_at: '2026-07-03T10:00:00Z',
    },
    success_criteria: {
      label: '성공기준',
      value: '',
      confidence: 20,
      source: 'ai_inferred',
      source_refs: [],
      updated_at: '2026-07-03T10:10:00Z',
    },
    features: {
      label: '기능',
      value: '출퇴근 기록, 휴가 신청/승인, 급여 명세, 조직도 관리',
      confidence: 55,
      source: 'document',
      source_refs: ['doc_001'],
      updated_at: '2026-07-03T10:00:00Z',
    },
    data: {
      label: '데이터',
      value: '',
      confidence: 15,
      source: 'ai_inferred',
      source_refs: [],
      updated_at: '2026-07-03T10:10:00Z',
    },
    admin: {
      label: '관리자',
      value: '인사팀장이 최고 관리자, 각 부서 팀장이 부서별 관리자',
      confidence: 45,
      source: 'ai_inferred',
      source_refs: ['doc_002'],
      updated_at: '2026-07-03T10:05:00Z',
    },
    integrations: {
      label: '외부연동',
      value: '',
      confidence: 10,
      source: 'ai_inferred',
      source_refs: [],
      updated_at: '2026-07-03T10:10:00Z',
    },
    budget: {
      label: '예산',
      value: '연 5천만원 이내 희망 (확정 아님)',
      confidence: 35,
      source: 'user',
      source_refs: [],
      updated_at: '2026-07-03T10:15:00Z',
    },
    timeline: {
      label: '일정',
      value: '2026년 내 1차 오픈 희망',
      confidence: 40,
      source: 'document',
      source_refs: ['doc_001'],
      updated_at: '2026-07-03T10:00:00Z',
    },
  },
  hypotheses: [
    {
      id: 'hyp_001',
      statement: 'SAP HR 데이터를 신규 시스템으로 마이그레이션해야 할 것으로 추정',
      confidence: 70,
      status: 'unconfirmed',
      related_section: 'data',
    },
    {
      id: 'hyp_002',
      statement: '모바일 앱이 필수 요구사항일 것으로 추정 (재택근무 환경)',
      confidence: 55,
      status: 'unconfirmed',
      related_section: 'features',
    },
  ],
  source_documents: [
    { doc_id: 'doc_001', name: 'RFP_인사시스템_전환_v2.pdf', type: 'pdf', status: 'processed' },
    { doc_id: 'doc_002', name: '현행_업무프로세스.pptx', type: 'pptx', status: 'processed' },
  ],
  interview_log: [],
}

export const mockMessages: InterviewMessage[] = [
  {
    id: 'msg_001',
    role: 'ai',
    content: '안녕하세요! 업로드해주신 2건의 문서를 분석했습니다.\n\n현재 전체 이해도는 **58%**입니다. 목적과 핵심 문제는 비교적 명확하지만, 성공기준·데이터·외부연동 영역의 정보가 부족합니다.\n\n가장 중요한 질문부터 시작하겠습니다.',
    timestamp: '2026-07-03T10:10:00Z',
    affected_sections: [],
  },
  {
    id: 'msg_002',
    role: 'ai',
    content: '이 프로젝트의 **성공기준**을 정의해 주실 수 있을까요?\n\n예를 들어:\n- 인사팀의 수작업 시간을 몇 % 줄이는 것이 목표인가요?\n- 시스템 도입 후 어떤 지표로 성공 여부를 판단하실 건가요?\n- 사용자 만족도, 처리 시간, 오류율 등 특정 KPI가 있나요?',
    timestamp: '2026-07-03T10:10:05Z',
    affected_sections: ['success_criteria'],
  },
]
